user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    max_length: 6
  reset:
    password: 2

user_helper:
  size: 80
  per_page: 20

users:
  index:
    size: 50

session_controller:
  session: 1
